language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    # grabbed this from astropy--to get scipy working, I think...
    - sudo apt-get update
install:
    - pip install --upgrade http://physics.mnstate.edu/craig/numpy-1.8.0-cp27-none-linux_x86_64.whl
    - pip install --upgrade http://physics.mnstate.edu/craig/astropy-0.3.1-cp27-none-linux_x86_64.whl
    - pip install coverage
    - pip install coveralls
    # need to install scripts because one test ends up invoking a subprocess
    - python setup.py install_scripts
script:
    coverage run --source=msumastro setup.py test
after_success:
    coveralls
