language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    # grabbed this from astropy--to get scipy working, I think...
    - sudo apt-get update
    - sudo apt-get install python-scipy python-numpy
install:
    - pip install Cython
    - pip install git+git://github.com/astropy/astropy
    # need to install scripts because one test ends up invoking a subprocess
    - python setup.py install_scripts
script:
    - python setup.py test
