language: python
python:
  - "2.7"

env:
    global:
        - NUMPY_VERSION=1.8.0
        - WHEELHOUSE=http://physics.mnstate.edu/craig/wheelhouse/numpy-$NUMPY_VERSION

before_install:
    # grabbed this from astropy--to get scipy working, I think...
    - sudo apt-get update
install:
    - pip install --use-wheel --find-links=$WHEELHOUSE --upgrade --force-reinstall numpy==$NUMPY_VERSION scipy astropy
    - pip install coverage
    - pip install coveralls
    # need to install scripts because one test ends up invoking a subprocess
    - python setup.py install_scripts
script:
    coverage run --source=msumastro setup.py test
after_success:
    coveralls
